const XAUUSD_SYMBOL = "XAU/USD";
const XAUUSD_DISPLAY_SYMBOL = "XAUUSD";
const DEFAULT_STRUCTURE_LOOKBACK = 120;
const DEFAULT_PIVOT_STRENGTH = 2;
const DEFAULT_TRENDLINE_PIVOTS = 6;

export {
  DEFAULT_PIVOT_STRENGTH,
  DEFAULT_STRUCTURE_LOOKBACK,
  DEFAULT_TRENDLINE_PIVOTS,
  XAUUSD_DISPLAY_SYMBOL,
  XAUUSD_SYMBOL,
};
